<<<<<<< HEAD
=======
import Header from "@/components/Header/Header";
import { TanstackQueryProvider } from "@/query/queryClient";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
>>>>>>> 595d65f39db3daba41e383fa72e5c4cfcd573ba2
import "./globals.css";
import Header from "./(providers)/(auth)/_components/Header";
import React, { ReactNode } from "react";

<<<<<<< HEAD
const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="ko">
      <head>
        <title>job-notice</title>
      </head>
      <body className="bg-gray-100">
        <Header />
        <main className="flex-1">{children}</main>
=======
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "비팔조",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQueryProvider>
          <Header />
          {children}
          <ReactQueryDevtools initialIsOpen={false} />
        </TanstackQueryProvider>
>>>>>>> 595d65f39db3daba41e383fa72e5c4cfcd573ba2
      </body>
    </html>
  );
};

export default RootLayout;
