const data = {
  currentCount: 196,
  data: [
    {
      "ISO alpha2": "GH",
      "ISO alpha3": "GHA",
      "ISO numeric": 288,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Ghana",
      한글명: "가나",
    },
    {
      "ISO alpha2": "GA",
      "ISO alpha3": "GAB",
      "ISO numeric": 266,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Gabon",
      한글명: "가봉",
    },
    {
      "ISO alpha2": "GY",
      "ISO alpha3": "GUY",
      "ISO numeric": 328,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Guyana",
      한글명: "가이아나",
    },
    {
      "ISO alpha2": "GM",
      "ISO alpha3": "GMB",
      "ISO numeric": 270,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Gambia",
      한글명: "감비아",
    },
    {
      "ISO alpha2": "GT",
      "ISO alpha3": "GTM",
      "ISO numeric": 320,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Guatemala",
      한글명: "과테말라",
    },
    {
      "ISO alpha2": "GD",
      "ISO alpha3": "GRD",
      "ISO numeric": 308,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Grenada",
      한글명: "그레나다",
    },
    {
      "ISO alpha2": "GR",
      "ISO alpha3": "GRC",
      "ISO numeric": 300,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Greece",
      한글명: "그리스",
    },
    {
      "ISO alpha2": "GN",
      "ISO alpha3": "GIN",
      "ISO numeric": 324,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Guinea",
      한글명: "기니",
    },
    {
      "ISO alpha2": "GW",
      "ISO alpha3": "GNB",
      "ISO numeric": 624,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Guinea-Bissau",
      한글명: "기니비사우",
    },
    {
      "ISO alpha2": "NA",
      "ISO alpha3": "NAM",
      "ISO numeric": 516,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Namibia",
      한글명: "나미비아",
    },
    {
      "ISO alpha2": "NR",
      "ISO alpha3": "NRU",
      "ISO numeric": 520,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Nauru",
      한글명: "나우루",
    },
    {
      "ISO alpha2": "NG",
      "ISO alpha3": "NGA",
      "ISO numeric": 566,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Nigeria",
      한글명: "나이지리아",
    },
    {
      "ISO alpha2": "SS",
      "ISO alpha3": "SSD",
      "ISO numeric": 728,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "South Sudan",
      한글명: "남수단",
    },
    {
      "ISO alpha2": "ZA",
      "ISO alpha3": "ZAF",
      "ISO numeric": 710,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "South Africa",
      한글명: "남아프리카공화국",
    },
    {
      "ISO alpha2": "NL",
      "ISO alpha3": "NLD",
      "ISO numeric": 528,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Netherlands",
      한글명: "네덜란드",
    },
    {
      "ISO alpha2": "NP",
      "ISO alpha3": "NPL",
      "ISO numeric": 524,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Nepal",
      한글명: "네팔",
    },
    {
      "ISO alpha2": "NO",
      "ISO alpha3": "NOR",
      "ISO numeric": 578,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Norway",
      한글명: "노르웨이",
    },
    {
      "ISO alpha2": "NZ",
      "ISO alpha3": "NZL",
      "ISO numeric": 554,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "New Zealand",
      한글명: "뉴질랜드",
    },
    {
      "ISO alpha2": "NU",
      "ISO alpha3": "NIU",
      "ISO numeric": 570,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Niue",
      한글명: "니우에",
    },
    {
      "ISO alpha2": "NE",
      "ISO alpha3": "NER",
      "ISO numeric": 562,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Niger",
      한글명: "니제르",
    },
    {
      "ISO alpha2": "NI",
      "ISO alpha3": "NIC",
      "ISO numeric": 558,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Nicaragua",
      한글명: "니카라과",
    },
    {
      "ISO alpha2": "DK",
      "ISO alpha3": "DNK",
      "ISO numeric": 208,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Denmark",
      한글명: "덴마크",
    },
    {
      "ISO alpha2": "DO",
      "ISO alpha3": "DOM",
      "ISO numeric": 214,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Dominican Republic",
      한글명: "도미니카공화국",
    },
    {
      "ISO alpha2": "DM",
      "ISO alpha3": "DMA",
      "ISO numeric": 212,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Dominica",
      한글명: "도미니카연방",
    },
    {
      "ISO alpha2": "DE",
      "ISO alpha3": "DEU",
      "ISO numeric": 276,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Germany",
      한글명: "독일",
    },
    {
      "ISO alpha2": "TL",
      "ISO alpha3": "TLS",
      "ISO numeric": 626,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Timor-Leste",
      한글명: "동티모르",
    },
    {
      "ISO alpha2": "LA",
      "ISO alpha3": "LAO",
      "ISO numeric": 418,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Laos",
      한글명: "라오스",
    },
    {
      "ISO alpha2": "LR",
      "ISO alpha3": "LBR",
      "ISO numeric": 430,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Liberia",
      한글명: "라이베리아",
    },
    {
      "ISO alpha2": "LV",
      "ISO alpha3": "LVA",
      "ISO numeric": 428,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Latvia",
      한글명: "라트비아",
    },
    {
      "ISO alpha2": "RU",
      "ISO alpha3": "RUS",
      "ISO numeric": 643,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Russia",
      한글명: "러시아",
    },
    {
      "ISO alpha2": "LB",
      "ISO alpha3": "LBN",
      "ISO numeric": 422,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Lebanon",
      한글명: "레바논",
    },
    {
      "ISO alpha2": "LS",
      "ISO alpha3": "LSO",
      "ISO numeric": 426,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Lesotho",
      한글명: "레소토",
    },
    {
      "ISO alpha2": "RO",
      "ISO alpha3": "ROU",
      "ISO numeric": 642,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Romania",
      한글명: "루마니아",
    },
    {
      "ISO alpha2": "LU",
      "ISO alpha3": "LUX",
      "ISO numeric": 442,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Luxembourg",
      한글명: "룩셈부르크",
    },
    {
      "ISO alpha2": "RW",
      "ISO alpha3": "RWA",
      "ISO numeric": 646,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Rwanda",
      한글명: "르완다",
    },
    {
      "ISO alpha2": "LY",
      "ISO alpha3": "LBY",
      "ISO numeric": 434,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아프리카",
      영문명: "Libya",
      한글명: "리비아",
    },
    {
      "ISO alpha2": "LT",
      "ISO alpha3": "LTU",
      "ISO numeric": 440,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Lithuania",
      한글명: "리투아니아",
    },
    {
      "ISO alpha2": "LI",
      "ISO alpha3": "LIE",
      "ISO numeric": 438,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Liechtenstein",
      한글명: "리히텐슈타인",
    },
    {
      "ISO alpha2": "MG",
      "ISO alpha3": "MDG",
      "ISO numeric": 450,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Madagascar",
      한글명: "마다가스카르",
    },
    {
      "ISO alpha2": "MH",
      "ISO alpha3": "MHL",
      "ISO numeric": 584,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Marshall Islands",
      한글명: "마셜제도",
    },
    {
      "ISO alpha2": "FM",
      "ISO alpha3": "FSM",
      "ISO numeric": 583,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Federated States of Micronesia",
      한글명: "마이크로네시아연방",
    },
    {
      "ISO alpha2": "MW",
      "ISO alpha3": "MWI",
      "ISO numeric": 454,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Malawi",
      한글명: "말라위",
    },
    {
      "ISO alpha2": "MY",
      "ISO alpha3": "MYS",
      "ISO numeric": 458,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Malaysia",
      한글명: "말레이시아",
    },
    {
      "ISO alpha2": "ML",
      "ISO alpha3": "MLI",
      "ISO numeric": 466,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Mali",
      한글명: "말리",
    },
    {
      "ISO alpha2": "MX",
      "ISO alpha3": "MEX",
      "ISO numeric": 484,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Mexico",
      한글명: "멕시코",
    },
    {
      "ISO alpha2": "MC",
      "ISO alpha3": "MCO",
      "ISO numeric": 492,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Monaco",
      한글명: "모나코",
    },
    {
      "ISO alpha2": "MA",
      "ISO alpha3": "MAR",
      "ISO numeric": 504,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아프리카",
      영문명: "Morocco",
      한글명: "모로코",
    },
    {
      "ISO alpha2": "MU",
      "ISO alpha3": "MUS",
      "ISO numeric": 480,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Mauritius",
      한글명: "모리셔스",
    },
    {
      "ISO alpha2": "MR",
      "ISO alpha3": "MRT",
      "ISO numeric": 478,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아프리카",
      영문명: "Mauritania",
      한글명: "모리타니아",
    },
    {
      "ISO alpha2": "MZ",
      "ISO alpha3": "MOZ",
      "ISO numeric": 508,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Mazambique",
      한글명: "모잠비크",
    },
    {
      "ISO alpha2": "ME",
      "ISO alpha3": "MNE",
      "ISO numeric": 499,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Montenegro",
      한글명: "몬테네그로",
    },
    {
      "ISO alpha2": "MD",
      "ISO alpha3": "MDA",
      "ISO numeric": 498,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Moldova",
      한글명: "몰도바",
    },
    {
      "ISO alpha2": "MV",
      "ISO alpha3": "MDV",
      "ISO numeric": 462,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Maldives",
      한글명: "몰디브",
    },
    {
      "ISO alpha2": "MT",
      "ISO alpha3": "MLT",
      "ISO numeric": 470,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Malta",
      한글명: "몰타",
    },
    {
      "ISO alpha2": "MN",
      "ISO alpha3": "MNG",
      "ISO numeric": 496,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Mongolia",
      한글명: "몽골",
    },
    {
      "ISO alpha2": "US",
      "ISO alpha3": "USA",
      "ISO numeric": 840,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "United States of America",
      한글명: "미국",
    },
    {
      "ISO alpha2": "MM",
      "ISO alpha3": "MMR",
      "ISO numeric": 104,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Myanmar",
      한글명: "미얀마",
    },
    {
      "ISO alpha2": "VU",
      "ISO alpha3": "VUT",
      "ISO numeric": 548,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Vanuatu",
      한글명: "바누아투",
    },
    {
      "ISO alpha2": "BH",
      "ISO alpha3": "BHR",
      "ISO numeric": 48,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Bahrain",
      한글명: "바레인",
    },
    {
      "ISO alpha2": "BB",
      "ISO alpha3": "BRB",
      "ISO numeric": 52,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Barbados",
      한글명: "바베이도스",
    },
    {
      "ISO alpha2": "VA",
      "ISO alpha3": "VAT",
      "ISO numeric": 336,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Vatican",
      한글명: "교황청",
    },
    {
      "ISO alpha2": "BS",
      "ISO alpha3": "BHS",
      "ISO numeric": 44,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Bahamas",
      한글명: "바하마",
    },
    {
      "ISO alpha2": "BD",
      "ISO alpha3": "BGD",
      "ISO numeric": 50,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Bangladesh",
      한글명: "방글라데시",
    },
    {
      "ISO alpha2": "BJ",
      "ISO alpha3": "BEN",
      "ISO numeric": 204,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Benin",
      한글명: "베냉",
    },
    {
      "ISO alpha2": "VE",
      "ISO alpha3": "VEN",
      "ISO numeric": 862,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Venezuela",
      한글명: "베네수엘라",
    },
    {
      "ISO alpha2": "VN",
      "ISO alpha3": "VNM",
      "ISO numeric": 704,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Vietnam",
      한글명: "베트남",
    },
    {
      "ISO alpha2": "BE",
      "ISO alpha3": "BEL",
      "ISO numeric": 56,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Belgium",
      한글명: "벨기에",
    },
    {
      "ISO alpha2": "BY",
      "ISO alpha3": "BLR",
      "ISO numeric": 112,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Belarus",
      한글명: "벨라루스",
    },
    {
      "ISO alpha2": "BZ",
      "ISO alpha3": "BLZ",
      "ISO numeric": 84,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Belize",
      한글명: "벨리즈",
    },
    {
      "ISO alpha2": "BA",
      "ISO alpha3": "BIH",
      "ISO numeric": 70,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Bosnia-Herzegovina",
      한글명: "보스니아헤르체고비나",
    },
    {
      "ISO alpha2": "BW",
      "ISO alpha3": "BWA",
      "ISO numeric": 72,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Botswana",
      한글명: "보츠와나",
    },
    {
      "ISO alpha2": "BO",
      "ISO alpha3": "BOL",
      "ISO numeric": 68,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Bolivia",
      한글명: "볼리비아",
    },
    {
      "ISO alpha2": "BI",
      "ISO alpha3": "BDI",
      "ISO numeric": 108,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Burundi",
      한글명: "부룬디",
    },
    {
      "ISO alpha2": "BF",
      "ISO alpha3": "BFA",
      "ISO numeric": 854,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Burkina Faso",
      한글명: "부르키나파소",
    },
    {
      "ISO alpha2": "BT",
      "ISO alpha3": "BTN",
      "ISO numeric": 64,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Bhutan",
      한글명: "부탄",
    },
    {
      "ISO alpha2": "MK",
      "ISO alpha3": "MKD",
      "ISO numeric": 807,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "North Macedonia",
      한글명: "북마케도니아",
    },
    {
      "ISO alpha2": "BG",
      "ISO alpha3": "BGR",
      "ISO numeric": 100,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Bulgaria",
      한글명: "불가리아",
    },
    {
      "ISO alpha2": "BR",
      "ISO alpha3": "BRA",
      "ISO numeric": 76,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Brazil",
      한글명: "브라질",
    },
    {
      "ISO alpha2": "BN",
      "ISO alpha3": "BRN",
      "ISO numeric": 96,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Brunei",
      한글명: "브루나이",
    },
    {
      "ISO alpha2": "WS",
      "ISO alpha3": "WSM",
      "ISO numeric": 882,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Samoa",
      한글명: "사모아",
    },
    {
      "ISO alpha2": "SA",
      "ISO alpha3": "SAU",
      "ISO numeric": 682,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Saudi Arabia",
      한글명: "사우디아라비아",
    },
    {
      "ISO alpha2": "CY",
      "ISO alpha3": "CYP",
      "ISO numeric": 196,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Cyprus",
      한글명: "사이프러스",
    },
    {
      "ISO alpha2": "SM",
      "ISO alpha3": "SMR",
      "ISO numeric": 674,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "San Marino",
      한글명: "산마리노",
    },
    {
      "ISO alpha2": "ST",
      "ISO alpha3": "STP",
      "ISO numeric": 678,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "S?o Tom? & Principe",
      한글명: "상투메프린시페",
    },
    {
      "ISO alpha2": "SN",
      "ISO alpha3": "SEN",
      "ISO numeric": 686,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Senegal",
      한글명: "세네갈",
    },
    {
      "ISO alpha2": "RS",
      "ISO alpha3": "SRB",
      "ISO numeric": 688,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Serbia",
      한글명: "세르비아",
    },
    {
      "ISO alpha2": "SC",
      "ISO alpha3": "SYC",
      "ISO numeric": 690,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Seychelles",
      한글명: "세이셸",
    },
    {
      "ISO alpha2": "LC",
      "ISO alpha3": "LCA",
      "ISO numeric": 662,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "St. Lucia",
      한글명: "세인트 루시아",
    },
    {
      "ISO alpha2": "VC",
      "ISO alpha3": "VCT",
      "ISO numeric": 670,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "St. Vincent & the Grenadines",
      한글명: "세인트 빈센트 그레나딘",
    },
    {
      "ISO alpha2": "KN",
      "ISO alpha3": "KNA",
      "ISO numeric": 659,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "St. Kitts-Nevis",
      한글명: "세인트 키츠 네비스",
    },
    {
      "ISO alpha2": "SO",
      "ISO alpha3": "SOM",
      "ISO numeric": 706,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Somalia",
      한글명: "소말리아",
    },
    {
      "ISO alpha2": "SB",
      "ISO alpha3": "SLB",
      "ISO numeric": 90,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Solomon Islands",
      한글명: "솔로몬제도",
    },
    {
      "ISO alpha2": "SD",
      "ISO alpha3": "SDN",
      "ISO numeric": 736,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Sudan",
      한글명: "수단",
    },
    {
      "ISO alpha2": "SR",
      "ISO alpha3": "SUR",
      "ISO numeric": 740,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Suriname",
      한글명: "수리남",
    },
    {
      "ISO alpha2": "LK",
      "ISO alpha3": "LKA",
      "ISO numeric": 144,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Sri Lanka",
      한글명: "스리랑카",
    },
    {
      "ISO alpha2": "SE",
      "ISO alpha3": "SWE",
      "ISO numeric": 752,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Sweden",
      한글명: "스웨덴",
    },
    {
      "ISO alpha2": "CH",
      "ISO alpha3": "CHE",
      "ISO numeric": 756,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Swiss",
      한글명: "스위스",
    },
    {
      "ISO alpha2": "ES",
      "ISO alpha3": "ESP",
      "ISO numeric": 724,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Spain",
      한글명: "스페인",
    },
    {
      "ISO alpha2": "SK",
      "ISO alpha3": "SVK",
      "ISO numeric": 703,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Slovakia",
      한글명: "슬로바키아",
    },
    {
      "ISO alpha2": "SI",
      "ISO alpha3": "SVN",
      "ISO numeric": 705,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Slovenia",
      한글명: "슬로베니아",
    },
    {
      "ISO alpha2": "SY",
      "ISO alpha3": "SYR",
      "ISO numeric": 760,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Syria",
      한글명: "시리아",
    },
    {
      "ISO alpha2": "SL",
      "ISO alpha3": "SLE",
      "ISO numeric": 694,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Sierra Leone",
      한글명: "시에라리온",
    },
    {
      "ISO alpha2": "SG",
      "ISO alpha3": "SGP",
      "ISO numeric": 702,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Singapore",
      한글명: "싱가포르",
    },
    {
      "ISO alpha2": "AE",
      "ISO alpha3": "ARE",
      "ISO numeric": 784,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "United Arab Emirates : UAE",
      한글명: "아랍에미리트",
    },
    {
      "ISO alpha2": "AM",
      "ISO alpha3": "ARM",
      "ISO numeric": 51,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Armenia",
      한글명: "아르메니아",
    },
    {
      "ISO alpha2": "AR",
      "ISO alpha3": "ARG",
      "ISO numeric": 32,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Argentina",
      한글명: "아르헨티나",
    },
    {
      "ISO alpha2": "IS",
      "ISO alpha3": "ISL",
      "ISO numeric": 352,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Iceland",
      한글명: "아이슬란드",
    },
    {
      "ISO alpha2": "HT",
      "ISO alpha3": "HTI",
      "ISO numeric": 332,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Haiti",
      한글명: "아이티",
    },
    {
      "ISO alpha2": "IE",
      "ISO alpha3": "IRL",
      "ISO numeric": 372,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Ireland",
      한글명: "아일랜드",
    },
    {
      "ISO alpha2": "AZ",
      "ISO alpha3": "AZE",
      "ISO numeric": 31,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "아시아",
      영문명: "Azerbaijan",
      한글명: "아제르바이잔",
    },
    {
      "ISO alpha2": "AF",
      "ISO alpha3": "AFG",
      "ISO numeric": 4,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Afghanistan",
      한글명: "아프가니스탄",
    },
    {
      "ISO alpha2": "AD",
      "ISO alpha3": "AND",
      "ISO numeric": 20,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Andorra",
      한글명: "안도라",
    },
    {
      "ISO alpha2": "AL",
      "ISO alpha3": "ALB",
      "ISO numeric": 8,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Albania",
      한글명: "알바니아",
    },
    {
      "ISO alpha2": "DZ",
      "ISO alpha3": "DZA",
      "ISO numeric": 12,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아프리카",
      영문명: "Algeria",
      한글명: "알제리",
    },
    {
      "ISO alpha2": "AO",
      "ISO alpha3": "AGO",
      "ISO numeric": 24,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Angola",
      한글명: "앙골라",
    },
    {
      "ISO alpha2": "AG",
      "ISO alpha3": "ATG",
      "ISO numeric": 28,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Antigua and Barbuda",
      한글명: "앤티가바부다",
    },
    {
      "ISO alpha2": "ER",
      "ISO alpha3": "ERI",
      "ISO numeric": 232,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Eritrea",
      한글명: "에리트레아",
    },
    {
      "ISO alpha2": "SZ",
      "ISO alpha3": "SWZ",
      "ISO numeric": 748,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Eswatini",
      한글명: "에스와티니",
    },
    {
      "ISO alpha2": "EE",
      "ISO alpha3": "EST",
      "ISO numeric": 233,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Estonia",
      한글명: "에스토니아",
    },
    {
      "ISO alpha2": "EC",
      "ISO alpha3": "ECU",
      "ISO numeric": 218,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Ecuador",
      한글명: "에콰도르",
    },
    {
      "ISO alpha2": "ET",
      "ISO alpha3": "ETH",
      "ISO numeric": 231,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Ethiopia",
      한글명: "에티오피아",
    },
    {
      "ISO alpha2": "SV",
      "ISO alpha3": "SLV",
      "ISO numeric": 222,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "El Salvador",
      한글명: "엘살바도르",
    },
    {
      "ISO alpha2": "GB",
      "ISO alpha3": "GBR",
      "ISO numeric": 826,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "United Kingdom",
      한글명: "영국",
    },
    {
      "ISO alpha2": "YE",
      "ISO alpha3": "YEM",
      "ISO numeric": 887,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Yemen",
      한글명: "예멘",
    },
    {
      "ISO alpha2": "OM",
      "ISO alpha3": "OMN",
      "ISO numeric": 512,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Oman",
      한글명: "오만",
    },
    {
      "ISO alpha2": "AT",
      "ISO alpha3": "AUT",
      "ISO numeric": 40,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Austria",
      한글명: "오스트리아",
    },
    {
      "ISO alpha2": "HN",
      "ISO alpha3": "HND",
      "ISO numeric": 340,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Honduras",
      한글명: "온두라스",
    },
    {
      "ISO alpha2": "JO",
      "ISO alpha3": "JOR",
      "ISO numeric": 400,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Jordan",
      한글명: "요르단",
    },
    {
      "ISO alpha2": "UG",
      "ISO alpha3": "UGA",
      "ISO numeric": 800,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Uganda",
      한글명: "우간다",
    },
    {
      "ISO alpha2": "UY",
      "ISO alpha3": "URY",
      "ISO numeric": 858,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Uruguay",
      한글명: "우루과이",
    },
    {
      "ISO alpha2": "UZ",
      "ISO alpha3": "UZB",
      "ISO numeric": 860,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "아시아",
      영문명: "Uzbekistan",
      한글명: "우즈베키스탄",
    },
    {
      "ISO alpha2": "UA",
      "ISO alpha3": "UKR",
      "ISO numeric": 804,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Ukraine",
      한글명: "우크라이나",
    },
    {
      "ISO alpha2": "IQ",
      "ISO alpha3": "IRQ",
      "ISO numeric": 368,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Iraq",
      한글명: "이라크",
    },
    {
      "ISO alpha2": "IR",
      "ISO alpha3": "IRN",
      "ISO numeric": 364,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Iran",
      한글명: "이란",
    },
    {
      "ISO alpha2": "IL",
      "ISO alpha3": "ISR",
      "ISO numeric": 376,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Israel",
      한글명: "이스라엘",
    },
    {
      "ISO alpha2": "EG",
      "ISO alpha3": "EGY",
      "ISO numeric": 818,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아프리카",
      영문명: "Egypt",
      한글명: "이집트",
    },
    {
      "ISO alpha2": "IT",
      "ISO alpha3": "ITA",
      "ISO numeric": 380,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Italia",
      한글명: "이탈리아",
    },
    {
      "ISO alpha2": "IN",
      "ISO alpha3": "IND",
      "ISO numeric": 356,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "India",
      한글명: "인도",
    },
    {
      "ISO alpha2": "ID",
      "ISO alpha3": "IDN",
      "ISO numeric": 360,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Indonesia",
      한글명: "인도네시아",
    },
    {
      "ISO alpha2": "JP",
      "ISO alpha3": "JPN",
      "ISO numeric": 392,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Japan",
      한글명: "일본",
    },
    {
      "ISO alpha2": "JM",
      "ISO alpha3": "JAM",
      "ISO numeric": 388,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Jamaica",
      한글명: "자메이카",
    },
    {
      "ISO alpha2": "ZM",
      "ISO alpha3": "ZMB",
      "ISO numeric": 894,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Zambia",
      한글명: "잠비아",
    },
    {
      "ISO alpha2": "GQ",
      "ISO alpha3": "GNQ",
      "ISO numeric": 226,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Equatorial Guinea",
      한글명: "적도기니",
    },
    {
      "ISO alpha2": "GE",
      "ISO alpha3": "GEO",
      "ISO numeric": 268,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "아시아",
      영문명: "Georgia",
      한글명: "조지아",
    },
    {
      "ISO alpha2": "CN",
      "ISO alpha3": "CHN",
      "ISO numeric": 156,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "China",
      한글명: "중국",
    },
    {
      "ISO alpha2": "CF",
      "ISO alpha3": "CAF",
      "ISO numeric": 140,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Central African Republic",
      한글명: "중앙아프리카공화국",
    },
    {
      "ISO alpha2": "DJ",
      "ISO alpha3": "DJI",
      "ISO numeric": 262,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Djibouti",
      한글명: "지부티",
    },
    {
      "ISO alpha2": "ZW",
      "ISO alpha3": "ZWE",
      "ISO numeric": 716,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Zimbabwe",
      한글명: "짐바브웨",
    },
    {
      "ISO alpha2": "TD",
      "ISO alpha3": "TCD",
      "ISO numeric": 148,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Chad",
      한글명: "차드",
    },
    {
      "ISO alpha2": "CZ",
      "ISO alpha3": "CZE",
      "ISO numeric": 203,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Czech",
      한글명: "체코",
    },
    {
      "ISO alpha2": "CL",
      "ISO alpha3": "CHL",
      "ISO numeric": 152,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Chile",
      한글명: "칠레",
    },
    {
      "ISO alpha2": "CM",
      "ISO alpha3": "CMR",
      "ISO numeric": 120,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Cameroon",
      한글명: "카메룬",
    },
    {
      "ISO alpha2": "CV",
      "ISO alpha3": "CPV",
      "ISO numeric": 132,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Cape Verde",
      한글명: "카보베르데",
    },
    {
      "ISO alpha2": "KZ",
      "ISO alpha3": "KAZ",
      "ISO numeric": 398,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "아시아",
      영문명: "Kazakhstan",
      한글명: "카자흐스탄",
    },
    {
      "ISO alpha2": "QA",
      "ISO alpha3": "QAT",
      "ISO numeric": 634,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Qatar",
      한글명: "카타르",
    },
    {
      "ISO alpha2": "KH",
      "ISO alpha3": "KHM",
      "ISO numeric": 116,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Cambodia",
      한글명: "캄보디아",
    },
    {
      "ISO alpha2": "CA",
      "ISO alpha3": "CAN",
      "ISO numeric": 124,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Canada",
      한글명: "캐나다",
    },
    {
      "ISO alpha2": "KE",
      "ISO alpha3": "KEN",
      "ISO numeric": 404,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Kenya",
      한글명: "케냐",
    },
    {
      "ISO alpha2": "KM",
      "ISO alpha3": "COM",
      "ISO numeric": 174,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Comoros",
      한글명: "코모로",
    },
    {
      "ISO alpha2": "XK",
      "ISO alpha3": "XKX",
      "ISO numeric": 383,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Kosovo",
      한글명: "코소보",
    },
    {
      "ISO alpha2": "CR",
      "ISO alpha3": "CRI",
      "ISO numeric": 188,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Costa Rica",
      한글명: "코스타리카",
    },
    {
      "ISO alpha2": "CI",
      "ISO alpha3": "CIV",
      "ISO numeric": 384,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "C?te D'Ivoire",
      한글명: "코트디부아르",
    },
    {
      "ISO alpha2": "CO",
      "ISO alpha3": "COL",
      "ISO numeric": 170,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Colombia",
      한글명: "콜롬비아",
    },
    {
      "ISO alpha2": "CG",
      "ISO alpha3": "COG",
      "ISO numeric": 178,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Congo",
      한글명: "콩고공화국",
    },
    {
      "ISO alpha2": "CD",
      "ISO alpha3": "COD",
      "ISO numeric": 180,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Democratic Republic of Congo",
      한글명: "콩고민주공화국(DR콩고)",
    },
    {
      "ISO alpha2": "CU",
      "ISO alpha3": "CUB",
      "ISO numeric": 192,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Cuba",
      한글명: "쿠바",
    },
    {
      "ISO alpha2": "KW",
      "ISO alpha3": "KWT",
      "ISO numeric": 414,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Kuwait",
      한글명: "쿠웨이트",
    },
    {
      "ISO alpha2": "CK",
      "ISO alpha3": "COK",
      "ISO numeric": 184,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Cook Islands",
      한글명: "쿡제도",
    },
    {
      "ISO alpha2": "HR",
      "ISO alpha3": "HRV",
      "ISO numeric": 191,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Croatia",
      한글명: "크로아티아",
    },
    {
      "ISO alpha2": "KG",
      "ISO alpha3": "KGZ",
      "ISO numeric": 417,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "아시아",
      영문명: "Kyrgyz",
      한글명: "키르기즈",
    },
    {
      "ISO alpha2": "KI",
      "ISO alpha3": "KIR",
      "ISO numeric": 296,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Kiribati",
      한글명: "키리바시",
    },
    {
      "ISO alpha2": "TJ",
      "ISO alpha3": "TJK",
      "ISO numeric": 762,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "아시아",
      영문명: "Tajikistan",
      한글명: "타지키스탄",
    },
    {
      "ISO alpha2": "TZ",
      "ISO alpha3": "TZA",
      "ISO numeric": 834,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Tanzania",
      한글명: "탄자니아",
    },
    {
      "ISO alpha2": "TH",
      "ISO alpha3": "THA",
      "ISO numeric": 764,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Thailand",
      한글명: "태국",
    },
    {
      "ISO alpha2": "TR",
      "ISO alpha3": "TUR",
      "ISO numeric": 792,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Turkey",
      한글명: "터키",
    },
    {
      "ISO alpha2": "TG",
      "ISO alpha3": "TGO",
      "ISO numeric": 768,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "아프리카",
      대륙명_행정표준코드: "아프리카",
      영문명: "Togo",
      한글명: "토고",
    },
    {
      "ISO alpha2": "TO",
      "ISO alpha3": "TON",
      "ISO numeric": 776,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Tonga",
      한글명: "통가",
    },
    {
      "ISO alpha2": "TM",
      "ISO alpha3": "TKM",
      "ISO numeric": 795,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "아시아",
      영문명: "Turkmenistan",
      한글명: "투르크메니스탄",
    },
    {
      "ISO alpha2": "TV",
      "ISO alpha3": "TUV",
      "ISO numeric": 798,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Tuvalu",
      한글명: "투발루",
    },
    {
      "ISO alpha2": "TN",
      "ISO alpha3": "TUN",
      "ISO numeric": 788,
      "대륙명_공통 대륙코드": "Africa",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아프리카",
      영문명: "Tunisia",
      한글명: "튀니지",
    },
    {
      "ISO alpha2": "TT",
      "ISO alpha3": "TTO",
      "ISO numeric": 780,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Trinidad & Tobago",
      한글명: "트리니다드토바고",
    },
    {
      "ISO alpha2": "PA",
      "ISO alpha3": "PAN",
      "ISO numeric": 591,
      "대륙명_공통 대륙코드": "North America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "북아메리카",
      영문명: "Panama",
      한글명: "파나마",
    },
    {
      "ISO alpha2": "PY",
      "ISO alpha3": "PRY",
      "ISO numeric": 600,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Paraguay",
      한글명: "파라과이",
    },
    {
      "ISO alpha2": "PK",
      "ISO alpha3": "PAK",
      "ISO numeric": 586,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Pakistan",
      한글명: "파키스탄",
    },
    {
      "ISO alpha2": "PG",
      "ISO alpha3": "PNG",
      "ISO numeric": 598,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Papua New Guinea :PNG",
      한글명: "파푸아뉴기니",
    },
    {
      "ISO alpha2": "PW",
      "ISO alpha3": "PLW",
      "ISO numeric": 585,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Palau",
      한글명: "팔라우",
    },
    {
      "ISO alpha2": "PS",
      "ISO alpha3": "PSE",
      "ISO numeric": 275,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "중동",
      대륙명_행정표준코드: "아시아",
      영문명: "Palestine",
      한글명: "팔레스타인",
    },
    {
      "ISO alpha2": "PE",
      "ISO alpha3": "PER",
      "ISO numeric": 604,
      "대륙명_공통 대륙코드": "South America",
      "대륙명_외교부 직제": "미주",
      대륙명_행정표준코드: "남아메리카",
      영문명: "Peru",
      한글명: "페루",
    },
    {
      "ISO alpha2": "PT",
      "ISO alpha3": "PRT",
      "ISO numeric": 620,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Portugal",
      한글명: "포르투갈",
    },
    {
      "ISO alpha2": "PL",
      "ISO alpha3": "POL",
      "ISO numeric": 616,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Poland",
      한글명: "폴란드",
    },
    {
      "ISO alpha2": "FR",
      "ISO alpha3": "FRA",
      "ISO numeric": 250,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "France",
      한글명: "프랑스",
    },
    {
      "ISO alpha2": "FJ",
      "ISO alpha3": "FJI",
      "ISO numeric": 242,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Fiji",
      한글명: "피지",
    },
    {
      "ISO alpha2": "FI",
      "ISO alpha3": "FIN",
      "ISO numeric": 246,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Finland",
      한글명: "핀란드",
    },
    {
      "ISO alpha2": "PH",
      "ISO alpha3": "PHL",
      "ISO numeric": 608,
      "대륙명_공통 대륙코드": "Asia",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "아시아",
      영문명: "Philippines",
      한글명: "필리핀",
    },
    {
      "ISO alpha2": "HU",
      "ISO alpha3": "HUN",
      "ISO numeric": 348,
      "대륙명_공통 대륙코드": "Europe",
      "대륙명_외교부 직제": "유럽",
      대륙명_행정표준코드: "유럽",
      영문명: "Hungary",
      한글명: "헝가리",
    },
    {
      "ISO alpha2": "AU",
      "ISO alpha3": "AUS",
      "ISO numeric": 36,
      "대륙명_공통 대륙코드": "Oceania",
      "대륙명_외교부 직제": "아주",
      대륙명_행정표준코드: "오세아니아",
      영문명: "Australia",
      한글명: "호주",
    },
  ],
  matchCount: 196,
  page: 1,
  perPage: 196,
  totalCount: 196,
};
